FROM node:8

WORKDIR /tmp
COPY . .


WORKDIR /tmp/mysite/draw_svg

RUN npm install && npm rebuild node-sass

RUN echo "npm run build && npm run build:copy && yarn build && yarn build:copy" > entrypoint.sh

ENTRYPOINT ["sh", "entrypoint.sh"]
