image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

stages:
  - build
  - test

build:
  stage: build
  script:
    - mv mysite/mysite/settings/local_example.py mysite/mysite/settings/local.py
    - mv fab_settings.py.example fab_settings.py
    - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
    - gunzip GeoLiteCity.dat.gz
    - mv GeoLiteCity.dat mysite/GeoLiteCityLocal.dat
    - docker build -f Dockerfile-ci -t gitlab-courselets-ci .

draw_svg:
  stage: test
  script: docker run gitlab-courselets-ci bash -c "cd draw_svg && yarn install && CI=true yarn test"

coverage:
  stage: test
  script: docker run gitlab-courselets-ci make coverage

quality:
  stage: test
  script: docker run gitlab-courselets-ci make quality
