image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

stages:
  - build
  - test

Build:
  stage: build
  tags:
    - docker
  script:
    - mv mysite/mysite/settings/local_example.py mysite/mysite/settings/local.py
    - mv fab_settings.py.example fab_settings.py
    - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
    - gunzip GeoLiteCity.dat.gz
    - mv GeoLiteCity.dat mysite/GeoLiteCityLocal.dat
    - docker build -f Dockerfile-ci -t $DOCKER_IMG_NAME:$CI_COMMIT_SHA .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_IMG_NAME:$CI_COMMIT_SHA

JavaScript tests:
  stage: test
  tags:
    - docker
  script:
    - docker run $DOCKER_IMG_NAME:$CI_COMMIT_SHA bash -c "cd draw_svg && yarn install && CI=true yarn test"

Python tests:
  stage: test
  tags:
    - docker
  script:
    - docker run $DOCKER_IMG_NAME:$CI_COMMIT_SHA make coverage

Check code quality:
  stage: test
  tags:
    - docker
  script:
    - docker run $DOCKER_IMG_NAME:$CI_COMMIT_SHA make quality
