variables:
  REGISTRY: registry-gitlab.raccoongang.com/cmltawt0/socraticqs2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - pre-build
  - build
  - test
  - tag
  - deploy
## - smoke
  - cleanup

Build static:
  interruptible: true
  stage: pre-build
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  script:
    - docker build
      --build-arg node_env=production
      -t $REGISTRY:static-$CI_COMMIT_SHORT_SHA
      -f Docker/Dockerfile.static .

Build base:
  interruptible: true
  stage: pre-build
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  script:
    - docker build
      -t $REGISTRY:base-$CI_COMMIT_SHORT_SHA
      -f Docker/Dockerfile .

Build Prod:
  interruptible: true
  stage: build
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  script:
    - docker build
      --force-rm
      -t $REGISTRY/courselets:$CI_COMMIT_SHORT_SHA
      -f Docker/Dockerfile.prod
      --build-arg REGISTRY=$REGISTRY
      --build-arg TAG=base-$CI_COMMIT_SHORT_SHA
      --build-arg STATIC_TAG=static-$CI_COMMIT_SHORT_SHA .

Build Test:
  interruptible: true
  stage: build
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  script:
    - docker build
      -t $REGISTRY/courselets-test:$CI_COMMIT_SHORT_SHA
      -f Docker/Dockerfile.test
      --build-arg REGISTRY=$REGISTRY
      --build-arg TAG=base-$CI_COMMIT_SHORT_SHA
      --build-arg STATIC_TAG=static-$CI_COMMIT_SHORT_SHA .

JavaScript tests:
  interruptible: true
  stage: test
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  script:
    - docker build -f Docker/Dockerfile-test.node -t node-test:$CI_COMMIT_SHORT_SHA .
    - docker run node-test:$CI_COMMIT_SHORT_SHA

Python tests:
  interruptible: true
  variables:
    GIT_STRATEGY: none
  stage: test
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  script:
    - docker run -d --name mongo_$CI_COMMIT_SHORT_SHA mongo:latest
    - docker run
      --volume ${PWD}/logs:/home/courselets/app/logs
      --volume ${PWD}/.git:/home/courselets/app/.git
      --rm
      --link mongo_$CI_COMMIT_SHORT_SHA:mongo
      $REGISTRY/courselets-test:$CI_COMMIT_SHORT_SHA
      make coverage
  after_script:
    - docker rm -f mongo_$CI_COMMIT_SHORT_SHA || true

Check code quality:
  interruptible: true
  stage: test
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  script:
    # .git volume requires for diff-quality. And it does not work :-\
    - docker run
      --volume ${PWD}/.git:/home/courselets/app/.git
      $REGISTRY/courselets-test:$CI_COMMIT_SHORT_SHA
      make quality

Tag latest courselets image:
  interruptible: true
  stage: tag
  tags:
    - dind
  only:
    - master
  script:
    - docker tag $REGISTRY/courselets:$CI_COMMIT_SHORT_SHA $REGISTRY/courselets
    - docker push $REGISTRY/courselets
  after_script:
    - docker rmi -f $REGISTRY/courselets:$CI_COMMIT_SHORT_SHA || true

Create a tag:
  interruptible: true
  stage: tag
  tags:
    - dind
  only:
    - tags
  script:
    - docker tag $REGISTRY/courselets:$CI_COMMIT_SHORT_SHA $REGISTRY/courselets:$CI_COMMIT_TAG
    - docker push $REGISTRY/courselets:$CI_COMMIT_TAG
  after_script:
    - docker rmi -f $REGISTRY/courselets:$CI_COMMIT_SHORT_SHA || true

Tag (cache) latest static image:
  interruptible: true
  stage: tag
  tags:
    - dind
  only:
    - master
    - tags
  script:
    - docker tag $REGISTRY:static-$CI_COMMIT_SHORT_SHA $REGISTRY/static
  after_script:
    - docker rmi -f $REGISTRY:static-$CI_COMMIT_SHORT_SHA || true

Deploy Dev:
  interruptible: true
  stage: deploy
  tags:
    - stage
    - deploy
    - ssh
  environment:
    name: development
    url: https://dev.courselets.org
  variables:
    DOCKER_REGISTRY: $REGISTRY
  only:
    - master
  script:
    - touch $DEV_APP_PWD/settings/local.py
    - docker pull ${DOCKER_REGISTRY}/courselets
    - docker-compose -f dev.yml up -d dev_app
    - docker-compose -f dev.yml run --rm dev_app migrate
    - docker-compose -f dev.yml run --rm dev_app fsm-deploy
    - docker-compose -f dev.yml run --rm dev_app static
    - curl "$SLACK_WEBHOOK_URL" -d 'payload={"text":"Development has been successfully deployed https://dev.courselets.org\n```\n'"$CI_COMMIT_MESSAGE"'\n```\n@redilonka (・ω・)", "link_names":1}'

## Run layout tests:
##   stage: smoke
##   tags:
##     - dind
##   only:
##     - development
##     - master
##   script:
##     - docker pull maxsocl/backstop:${CI_COMMIT_REF_NAME}
##     - docker run maxsocl/backstop:${CI_COMMIT_REF_NAME}

Deploy Stage:
  interruptible: true
  stage: deploy
  tags:
    - stage
    - deploy
    - ssh
  environment:
    name: staging
    url: https://staging.courselets.org
  when: manual
  allow_failure: false
  only:
    - tags
  variables:
    DOCKER_REGISTRY: $REGISTRY
    IMAGE_TAG: $CI_COMMIT_TAG
  script:
    - touch $APP_PWD/settings/local.py
    - docker pull ${DOCKER_REGISTRY}/courselets:${IMAGE_TAG}
    - docker-compose -f prod.yml up -d app
    - docker-compose -f prod.yml run --rm app migrate
    - docker-compose -f prod.yml run --rm app fsm-deploy
    - docker-compose -f prod.yml run --rm app static
    - curl "$SLACK_WEBHOOK_URL" -d 'payload={"text":"Staging has been successfully deployed https://staging.courselets.org```\n'"$CI_COMMIT_MESSAGE"'\n```\n@redilonka (・ω・)", "link_names":1}'
    - curl "$CR_SLACK_WEBHOOK_URL" -d 'payload={"text":"Staging has been successfully deployed https://staging.courselets.org```\n'"$CI_COMMIT_MESSAGE"'\n```\n@here", "link_names":1}'

Cleanup:
  stage: cleanup
  tags:
    - dind
  only:
    - master
    - merge_requests
    - tags
  when: always
  script:
    - docker rmi -f $REGISTRY:static-$CI_COMMIT_SHORT_SHA || true
    - docker rmi -f $REGISTRY:base-$CI_COMMIT_SHORT_SHA || true
    - docker rmi -f $REGISTRY/courselets:$CI_COMMIT_SHORT_SHA || true
    - docker rmi -f $REGISTRY/courselets:CI_COMMIT_TAG || true
