image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info
- docker ps

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  tags:
    - docker
  script:
    - cp .circleci/.dockerignore ./
    - docker build -f Dockerfile.CI -t $DOCKER_IMG_NAME:$CI_COMMIT_SHA .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_IMG_NAME:$CI_COMMIT_SHA

JavaScript tests:
  stage: test
  tags:
    - docker
  script:
    - docker run $DOCKER_IMG_NAME:$CI_COMMIT_SHA bash -c "cd draw_svg && yarn install && CI=true yarn test"

Python tests:
  stage: test
  tags:
    - docker
  script:
    - docker run -d --name mongo -p 27017:27017 mongo:latest
    - docker run --link mongo:mongo $DOCKER_IMG_NAME:$CI_COMMIT_SHA make coverage

Check code quality:
  stage: test
  tags:
    - docker
  script:
    - docker run $DOCKER_IMG_NAME:$CI_COMMIT_SHA make quality

Deploy Dev:
  stage: deploy
  tags:
    - stage
    - deploy
    - ssh
  environment:
    name: development
    url: https://dev.courselets.org
  only:
    - development
  script:
    - cd /home/wwwapps/dev/socraticqs2/
    - git fetch
    - git reset --hard origin/development
    - source /home/wwwapps/dev/_ve_socraticqs2/bin/activate
    - pip install --ignore-installed -U -r requirements.txt
    - pip install --ignore-installed -U -r requirements/prod.txt
    - cd mysite/
    - python manage.py migrate
    - python manage.py fsm_deploy
    - cd draw_svg/
    - npm install --save-dev
    - npm run build && npm run build:copy-local
    - yarn build && yarn build:copy-local
    - cd ..
    - python manage.py collectstatic --noinput
    - sudo supervisorctl restart devgunicorn
    - sudo supervisorctl restart devcelery
    - curl "$SLACK_WEBHOOK_URL" -d 'payload={"text":"Development has been successfully deployed https://dev.courselets.org\n@redilonka (・ω・)", "link_names":1}'

Deploy Stage:
  stage: deploy
  tags:
    - stage
    - deploy
    - ssh
  only:
    - master
  script:
    - cd /home/wwwapps/socraticqs2/
    - git fetch
    - git reset --hard origin/master
    - source /home/wwwapps/_ve_socraticqs3/bin/activate
    - pip install --ignore-installed -U -r requirements.txt
    - pip install --ignore-installed -U -r requirements/prod.txt
    - cd mysite/
    - python manage.py migrate
    - python manage.py fsm_deploy
    - cd draw_svg/
    - npm install --save-dev
    - npm run build && npm run build:copy-local
    - yarn build && yarn build:copy-local
    - cd ..
    - python manage.py collectstatic --noinput
    - sudo supervisorctl restart gunicorn
    - sudo supervisorctl restart celery
    - curl "$SLACK_WEBHOOK_URL" -d 'payload={"text":"Staging has been successfully deployed https://staging.courselets.org\n@redilonka (・ω・)", "link_names":1}'
