image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

stages:
  - build
  - test

job 1:
  stage: build
  script:
    - mv mysite/mysite/settings/local_example.py mysite/mysite/settings/local.py
    - mv fab_settings.py.example fab_settings.py
    - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
    - gunzip GeoLiteCity.dat.gz
    - mv GeoLiteCity.dat mysite/GeoLiteCityLocal.dat
    - docker build -f Dockerfile-ci -t gitlab-courselets-ci .
    - apt-get -y update && apt-get install -y nodejs

job 2:
  stage: test
  script: docker run gitlab-courselets-ci make coverage

job 3:
  stage: test
  script: docker run gitlab-courselets-ci bash -c "cd mysite/draw_svg && npm install && CI=true npm run test"

job 4:
  stage: test
  script: docker run gitlab-courselets-ci make quality
