image: ubuntu:14.04

services:
  - postgres:9.6

before_script:
  - apt-get -y update && apt-get install -y pandoc python2.7 python-pip git python-dev libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev wget phantomjs
  - pip install -r requirements/test.txt
  - mv mysite/mysite/settings/local_example.py mysite/mysite/settings/local.py
  - mv fab_settings.py.example fab_settings.py
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - mv GeoLiteCity.dat mysite/GeoLiteCityLocal.dat

stages:
  - tests

run python tests:
  stage: tests
  script:
    - cd mysite
    - pytest
