version: '3'
services:
  dev_app:
    container_name: dev_cr_app
    env_file: ./envs/dev.env
    image: maxsocl/courselets:development
    command: python manage.py runserver 0.0.0.0:8080 --settings=mysite.settings.docker
    volumes:
      - ${PWD}/mysite/mysite/settings/local.py:/app/mysite/mysite/settings/local.py
    ports:
      - "8080:8080"
    links:
      - dev_postgres
      - dev_mongo
      - dev_memcached
      - dev_celery

  dev_postgres:
    container_name: dev_cr_postgres
    image: postgres:9.6
    env_file: ./envs/dev.env
    volumes:
      - dev_cr_db:/var/lib/postgresql/data/

  dev_mongo:
    container_name: dev_cr_mongo
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - dev_cr_mongo:/data/db
  
  dev_memcached:
    container_name: dev_cr_memcached
    image: memcached:latest
  
  dev_celery:
    container_name: dev_cr_celery
    image: maxsocl/cr.celery:development
    command: celery worker -A mysite --loglevel=INFO -B
    env_file: ./envs/dev.env
    links:
      - dev_rabbit
      - dev_redis

  dev_rabbit:
    container_name: dev_cr_rabbit
    image: rabbitmq:latest
  
  dev_redis:
    container_name: dev_cr_redis
    image: redis:latest

volumes:
  dev_cr_db:
  dev_cr_mongo:
