version: '3'
services:
  dev_app:
    container_name: dev_cr_app
    env_file: ./envs/dev.env
    # image: maxsocl/courselets:development
    # image: registry-gitlab.raccoongang.com/cmltawt0/socraticqs2:default
    image: ${DOCKER_REGISTRY}:courselets-dev
    command: ["dev"]
    volumes:
      # file should exist on host (even if empty) or docker will create a directory instead
      - ${PWD}/mysite/mysite/settings/local.py:/home/courselets/app/mysite/mysite/settings/local.py
      - ${PWD}/logs:/home/courselets/app/logs
    ports:
      - "8080:8080"
    links:
      - dev_postgres
      - dev_mongo
      - dev_memcached
      - dev_celery
    environment:
      - DOCKER_REGISTRY

  dev_postgres:
    container_name: dev_cr_postgres
    image: postgres:9.6
    env_file: ./envs/dev.env
    volumes:
      - dev_cr_db:/var/lib/postgresql/data/

  dev_mongo:
    container_name: dev_cr_mongo
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - dev_cr_mongo:/data/db

  dev_memcached:
    container_name: dev_cr_memcached
    image: memcached:latest

  dev_celery:
    environment:
      - DOCKER_REGISTRY
      - CELERY_BROKER_URL=amqp://guest@dev_rabbit
    container_name: dev_cr_celery
    # user: courselets
    # image: maxsocl/cr.celery:development
    # image: registry-gitlab.raccoongang.com/cmltawt0/socraticqs2:celery
    image: ${DOCKER_REGISTRY}:courselets-dev
    command: celery worker -A mysite --loglevel=INFO -B
    env_file: ./envs/dev.env
    volumes:
      - .:/home/courselets/app
    links:
      - dev_rabbit
      - dev_redis

  dev_rabbit:
    container_name: dev_cr_rabbit
    image: rabbitmq:latest
  
  dev_redis:
    container_name: dev_cr_redis
    image: redis:latest

volumes:
  dev_cr_db:
  dev_cr_mongo:
