version: '3'
services:
  local_app:
    container_name: local_cr_app
    env_file: ./envs/local.env
    image: local/courselets:courselets-local
    build:
      context: .
      dockerfile: Docker/Dockerfile.dev
    command: ["local"]
    volumes:
      - ./:/home/courselets/app
    ports:
      - "8080:8080"
    links:
      - local_postgres
      - local_mongo
      - local_memcached
      - local_celery

  local_postgres:
    container_name: local_cr_postgres
    image: postgres:11.5
    env_file: ./envs/local.env
    volumes:
      - local_cr_db:/var/lib/postgresql/data/

  local_mongo:
    container_name: local_cr_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - local_cr_mongo:/data/db
 
  local_memcached:
    container_name: local_cr_memcached
    image: memcached:latest

  local_celery:
    environment:
      - CELERY_BROKER_URL=amqp://guest@local_rabbit
    container_name: local_cr_celery
    # image already built as local_app service
    image: local/courselets:courselets-local
    command: celery worker -A mysite --loglevel=INFO -B
    env_file: ./envs/local.env
    volumes:
      - .:/home/courselets/app/
    links:
      - local_rabbit
      - local_redis

  local_rabbit:
    container_name: local_cr_rabbit
    image: rabbitmq:latest
  
  local_redis:
    container_name: local_cr_redis
    image: redis:latest

volumes:
  local_cr_db:
  local_cr_mongo:
