version: '2'
services:
  courselets:
    container_name: courselets
    env_file: ./envs/local.env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh /courselets/docker-commands.sh
    volumes:
      - .:/courselets
    ports:
      - "8000:8000"
    links:
      - postgres

  postgres:
    container_name: cr_postgres
    image: postgres:9.6
    env_file: ./envs/local.env
    volumes:
      - cr_db:/var/lib/postgresql/data/

volumes:
  cr_db:
