# Dockerfile to prepare base image maxsocl/courselets:dev
FROM phusion/baseimage
RUN apt-get -y update && apt-get install -y \
    pandoc \
    python2.7 \
    python-pip \
    git \
    libpq-dev \
    libxml2-dev \
    libxslt1-dev \
    python-dev \
    zlib1g-dev
COPY requirements.txt .
RUN mkdir /requirements
COPY requirements/base.txt ./requirements
COPY requirements/dev.txt ./requirements
COPY requirements/prod.txt ./requirements
COPY requirements/test.txt ./requirements
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt
RUN pip install -r /requirements/dev.txt
RUN pip install -r /requirements/prod.txt
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code/mysite
