from django.conf.urls import patterns, include, url
from ct.views import *

urlpatterns = patterns('',
    (r'^$', main_page),
    url(r'^teach/$', teach, name='teach'),
    url(r'^courses/$', courses, name='courses'),
    url(r'^courses/(?P<course_id>\d+)/$', course, name='course'),
    url(r'^courses/(?P<course_id>\d+)/study/$', course_study, name='course_study'),
    url(r'^units/(?P<unit_id>\d+)/$', unit, name='unit'),
    url(r'^units/(?P<unit_id>\d+)/wait/$', unit_wait, name='unit_wait'),
    url(r'^concepts/$', concepts, name='concepts'),
    url(r'^concepts/(?P<concept_id>\d+)/$', concept, name='concept'),
    url(r'^questions/$', questions, name='questions'),
    url(r'^questions/(?P<ct_id>\d+)/$', question, name='question'),
    url(r'^questions/(?P<ct_id>\d+)/studylist/$', flag_question, name='flag_question'),
    url(r'^questions/(?P<ct_id>\d+)/respond/$', respond, name='respond'),
    url(r'^questions/(?P<ct_id>\d+)/concept/$', question_concept, name='question_concept'),
    url(r'^unitq/(?P<unitq_id>\d+)/$', unitq, name='unitq'),
    url(r'^unitq/(?P<unitq_id>\d+)/respond/$', respond_unitq, name='respond_unitq'),
    url(r'^unitq/(?P<unitq_id>\d+)/start/$', unitq_live_start, name='livestart'),
    url(r'^unitq/(?P<unitq_id>\d+)/control/$', unitq_control, name='control'),
    url(r'^unitq/(?P<unitq_id>\d+)/end/$', unitq_end, name='end'),
    url(r'^unitq/(?P<unitq_id>\d+)/wait/$', wait, name='wait'),
    url(r'^unitq/(?P<unitq_id>\d+)/concept/$', unitq_concept, name='unitq_concept'),
    url(r'^resp/(?P<resp_id>\d+)/assess/$', assess, name='assess'),
    url(r'^err/(?P<em_id>\d+)/$', error_model, name='error_model'),
    url(r'^err/(?P<em_id>\d+)/remedy/$', remedy_page, name='remedy'),
    url(r'^err/(?P<em_id>\d+)/remediate/$', submit_remedy, name='remediate'),
    url(r'^remediations/(?P<rem_id>\d+)/$', remediation, name='remediation'),
    url(r'^gloss/(?P<glossary_id>\d+)/write/$', glossary_page, name='write_glossary'),
    url(r'^gloss/(?P<glossary_id>\d+)/new_term/$', submit_term, name='new_term'),

)

