# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0024_auto_20180512_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
