# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0027_role_trial_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
