# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-29 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0028_response_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_show_will_learn',
            field=models.BooleanField(default=False),
        ),
    ]
