# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-25 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0028_auto_20181022_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirycount',
            name='status',
            field=models.CharField(choices=[(b'help', b'Still confused, need help'), (b'review', b'OK, but flag this for me to review'), (b'done', b'Solidly')], max_length=10, null=True),
        ),
    ]
