# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-31 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0029_unit_is_show_will_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='FSM_flow',
            field=models.CharField(choices=[(b'chat', b'Default FSM flow'), (b'chat_trial', b'Trial FSM flow - ABORTS before Student answer')], default=b'chat', max_length=10),
        ),
    ]
