# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0029_inquirycount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_number',
            field=models.PositiveIntegerField(blank=True, default=200, null=True),
        ),
    ]
