# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 12:45
from __future__ import unicode_literals

import ct.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0030_course_students_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='assessment_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='unit',
            name='best_practice_type',
            field=models.CharField(blank=True, choices=[(b'practice', b'Practice-exam'), (b'prereq', b'Prereq inventory'), (b'mission', b'Mission training'), (b'in_class', b'In-class')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='deadline',
            field=models.IntegerField(blank=True, null=True, validators=[ct.models.percent_validator]),
        ),
        migrations.AddField(
            model_name='unit',
            name='durations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='follow_up_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='follow_up_assessment_grade',
            field=models.IntegerField(blank=True, null=True, validators=[ct.models.percent_validator]),
        ),
        migrations.AddField(
            model_name='unit',
            name='participation_credit',
            field=models.IntegerField(blank=True, null=True, validators=[ct.models.percent_validator]),
        ),
        migrations.AddField(
            model_name='unit',
            name='practice_questions',
            field=models.FileField(blank=True, null=True, upload_to=b'practice_questions/', validators=[django.core.validators.FileExtensionValidator([b'pdf', b'docx'])]),
        ),
    ]
