# Generated by Django 2.1.11 on 2019-08-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0032_course_best_practice1'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='misconceptions_per_day',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='assessment_name',
            field=models.CharField(blank=True, default='Midterm 1', max_length=30),
        ),
    ]
