# Generated by Django 2.1.11 on 2019-08-15 06:58

import ct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0034_auto_20190814_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='deadline',
            new_name='average_score',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='participation_credit',
            new_name='courselet_completion_credit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='durations',
            new_name='courselet_days',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='best_practice_type',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='practice_questions',
        ),
        migrations.AddField(
            model_name='unit',
            name='courselet_deadline',
            field=models.IntegerField(blank=True, null=True, validators=[ct.models.percent_validator]),
        ),
        migrations.AddField(
            model_name='unit',
            name='error_resolution_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='graded_assessment_value',
            field=models.IntegerField(blank=True, null=True, validators=[ct.models.percent_validator]),
        ),
        migrations.AddField(
            model_name='unit',
            name='late_completion_penalty',
            field=models.IntegerField(blank=True, null=True, validators=[ct.models.percent_validator]),
        ),
        migrations.AddField(
            model_name='unit',
            name='question_parts',
            field=models.IntegerField(blank=True, null=True, validators=[ct.models.percent_validator]),
        ),
    ]
