# Generated by Django 2.1.11 on 2019-08-15 09:25

import ct.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0035_auto_20190814_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='practice_questions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='courselet_completion_credit',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[ct.models.percent_validator]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='late_completion_penalty',
            field=models.IntegerField(blank=True, default=50, null=True, validators=[ct.models.percent_validator]),
        ),
    ]
