# Generated by Django 2.1.11 on 2019-08-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0036_auto_20190815_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='upload_file',
        ),
    ]
