# Generated by Django 2.1.12 on 2019-11-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0037_remove_unit_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faq_threshold',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='response',
            name='faq_notified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
