# Generated by Django 2.1.12 on 2019-11-25 21:39

import ct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0041_auto_20191125_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='courselet_days',
            field=models.IntegerField(blank=True, help_text='2', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='error_resolution_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='follow_up_assessment_grade',
            field=models.IntegerField(blank=True, default=15, null=True, validators=[ct.models.percent_validator]),
        ),
    ]
