# Generated by Django 2.1.12 on 2019-11-26 16:40

import ct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0042_auto_20191125_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='graded_assessment_datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='graded_assessment_value',
            field=models.IntegerField(blank=True, default=15, null=True, validators=[ct.models.percent_validator]),
        ),
    ]
