# Generated by Django 2.1.15 on 2020-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0043_auto_20191126_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
