# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install pandoc
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt -U pip

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
            name: Prepare environment
            command: |
              mv mysite/mysite/settings/local_example.py mysite/mysite/settings/local.py
              mv fab_settings.py.example fab_settings.py
              wget -c http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
              echo Dowloaded DB
              gunzip GeoLiteCity.dat.gz
              mv GeoLiteCity.dat mysite/GeoLiteCityLocal.dat

      # run tests!
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd mysite
            pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
