# Generated by Django 2.1.12 on 2020-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20200106_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.IntegerField(null=True),
        ),
    ]
