ARG REGISTRY=local/courselets
ARG TAG=base-local
ARG STATIC_TAG=static-local

FROM $REGISTRY:$STATIC_TAG as static


FROM $REGISTRY:$TAG

USER courselets

ADD --chown=courselets:courselets mysite /home/courselets/app/mysite
COPY --from=static --chown=courselets:courselets /drawing.bundle.js lms/static/js/drawing.bundle.js
COPY --from=static --chown=courselets:courselets /tmp/mysite/frontend/bower_components chat/static/bower_components

CMD ["prod"]
