ARG REGISTRY=local/courselets
ARG TAG=base-local
ARG STATIC_TAG=static-local

FROM $REGISTRY:$STATIC_TAG as static


FROM $REGISTRY:$TAG

RUN apt-get -y update && \
	apt-get install -y \
	libpq-dev \
	libxml2-dev \
	libxslt1-dev \
	make \
	phantomjs \
	python3-dev \
	wget \
	zlib1g-dev \
	&& rm -rf /var/lib/apt/lists/*
RUN pip install --ignore-installed -U -r /requirements/dev.txt

USER courselets

ADD --chown=courselets:courselets mysite /home/courselets/app/mysite
COPY --from=static --chown=courselets:courselets /drawing.bundle.js lms/static/js/drawing.bundle.js
COPY --from=static --chown=courselets:courselets /tmp/mysite/frontend/bower_components chat/static/bower_components
COPY --from=static --chown=courselets:courselets /tmp/mysite/ctms/frontend/dist/add_threads.bundle.js lms/static/js/add_threads.bundle.js

CMD ["dev"]
