FROM node:8

ARG node_env=production
ENV NODE_ENV=$node_env

COPY mysite/draw_svg /tmp/mysite/draw_svg
COPY mysite/frontend /tmp/mysite/frontend

WORKDIR /tmp/mysite/draw_svg

RUN npm i
RUN npm run build && npm run build:copy

WORKDIR /tmp/mysite/frontend
RUN yarn
