ARG REGISTRY=local/courselets
ARG TAG=base-local
ARG STATIC_TAG=static-local

FROM $REGISTRY:$STATIC_TAG as static


FROM $REGISTRY:$TAG

RUN apt-get -y update && \
	apt-get install -y \
	gcc \
	make \
	python3-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN pip install --ignore-installed -U -r /requirements/test.txt

ADD --chown=courselets:courselets mysite /home/courselets/app/mysite
COPY --from=static --chown=courselets:courselets /draw_svg.js lms/static/js/draw_svg.js
COPY --from=static --chown=courselets:courselets /draw_svg.css lms/static/css/draw_svg.css
COPY --from=static --chown=courselets:courselets /tmp/mysite/frontend/bower_components chat/static/bower_components
RUN touch mysite/settings/local.py
