ARG REGISTRY=local/courselets
ARG TAG=base-latest
# ARG STATIC_REG=local/static
ARG STATIC_TAG=static-latest

FROM $REGISTRY:$STATIC_TAG as static


FROM $REGISTRY:$TAG

USER courselets

ADD mysite /home/courselets/app/mysite
COPY --from=static /draw_svg.js lms/static/js/draw_svg.js
COPY --from=static /draw_svg.css lms/static/css/draw_svg.css
COPY --from=static /tmp/mysite/frontend/bower_components chat/static/bower_components

CMD ["prod"]
