# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180530_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='what_do_you_teach',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
