from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20151106_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelearningratesplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bannerplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='benefitsitemplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='benefitsplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='childpersonalguidesplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='detailschildplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='detailsquoteplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='detailsvideoplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='faqitemplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='faqplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='footerplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='interestedplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='landingplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='listplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='miscitemplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='parentpersonalguidesplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='socialplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='workshopdescriptionplugin',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=True,
        ),
    ]
