# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_keynoteplugin_keynotessetplugin_proofplugin_socialproofsplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keynoteplugin',
            name='uid',
            field=models.SlugField(max_length=8),
        ),
    ]
