# Generated by Django 2.1.11 on 2019-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_hero1model_hero2model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedplugin',
            name='description',
            field=models.TextField(default='Get on our mailing list and we’ll contact you about the next hackathon.'),
        ),
        migrations.AlterField(
            model_name='interestedplugin',
            name='title',
            field=models.CharField(default='I’m Interested in the hackathon', max_length=200),
        ),
    ]
