# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20181116_0657'),
        ('ctms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='enroll_unit_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.EnrollUnitCode'),
        ),
    ]
