# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctms', '0003_auto_20181129_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPractices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField(verbose_name=b'How many students do you have in your class?')),
                ('misconceptions_count', models.IntegerField(verbose_name=b'How many individual student misconceptions in your class did you fix today (or your average teaching day)?')),
                ('question_count', models.IntegerField(verbose_name=b'Number of question-parts in your typical exam (e.g. 8 questions with 3 parts each = 24)?')),
                ('mean_percent', models.IntegerField(verbose_name=b'Mean percent score on this exam?')),
                ('activate', models.BooleanField()),
                ('estimated_blindspots', models.IntegerField(blank=True)),
                ('estimated_blindspots_courselets', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
