# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctms', '0004_bestpractices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPractices2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_engaged', models.IntegerField(verbose_name=b'What percent of students are fully engaged, i.e. would immediately do any optional exercises you provide, just to improve their understanding?')),
                ('activate', models.BooleanField()),
                ('estimated_blindspots', models.IntegerField(blank=True)),
                ('estimated_blindspots_courselets', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
