# Generated by Django 2.1.11 on 2019-08-03 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0004_bestpractice1_bestpractice2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpractice1',
            name='activate',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bestpractice1',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='best_practices/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='bestpractice2',
            name='activate',
            field=models.BooleanField(blank=True),
        ),
    ]
