# Generated by Django 2.1.11 on 2019-08-12 07:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0032_course_best_practice1'),
        ('ctms', '0005_auto_20190803_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.Course')),
                ('courselet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='BestPracticeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('metric', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('course', 'Course'), ('courselet', 'Courselet')], db_index=True, max_length=10)),
                ('calculation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bestpractice',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctms.BestPracticeTemplate'),
        ),
    ]
