# Generated by Django 2.1.11 on 2019-08-15 09:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0008_auto_20190814_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpracticetemplate',
            name='actication',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
