# Generated by Django 2.1.11 on 2019-08-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0009_bestpracticetemplate_actication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestpracticetemplate',
            old_name='actication',
            new_name='activation',
        ),
    ]
