# Generated by Django 2.1.11 on 2019-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0010_auto_20190815_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpracticetemplate',
            name='summary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
