# Generated by Django 2.1.11 on 2019-08-22 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0011_bestpracticetemplate_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpractice',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='practice_questions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
