# Generated by Django 2.1.12 on 2019-11-19 08:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0013_auto_20191014_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpractice',
            name='converted_status',
            field=models.CharField(choices=[('pending', 'Document uploaded, conversion in progress, etc.'), ('review', 'Conversion completed, please review ...'), ('done', 'Conversion completed, reviewed, X threads created.')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='bestpracticetemplate',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bestpracticetemplate',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='bestpractice',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='practice_questions/'),
        ),
    ]
