# Generated by Django 2.1.12 on 2019-11-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0014_auto_20191119_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpractice',
            name='converted_status',
            field=models.CharField(choices=[('pending', 'it will be converted shortly'), ('done', 'it has been converted')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
